### ISSUE TITLE
broken image link to example usage in `readme.md`

### ISSUE THREAD

**Issue by raffaelj** [pauloamgomes/Cockpit-MultipleCollectionLink#1]
The image url doesn't point to an actual image, but you could embed it with:
`https://api.monosnap.com/rpc/file/download?id=HwyRbyxwEBJeuyTyoyAiBuRDCMz7Ex`

or directly with:
`https://d1ro8r1rbfn3jf.cloudfront.net/ms_113506/U0saJwaMT9LWMvh8aijLRfl9q5Kzji/cockpitcms-multiplelinkcollection.gif?Expires=1527757657&Signature=bItxadGpwkcRPD9PkDKND4HlkKjItT1eXQBhNddBUDde2UGzRJu-9mq-4CC208VHq5Y96mZo2VzGr152ydMK2H9LiLbDDhWYfydYz0cCD7NYeF9QxVjAac0xNWuAXV4s96GrWy~uM-mKQQlgtr2ahMtXv98-TDvxSQia4V2GESwjKJIwhlzvClkZHD30r22n22RDjTHEwq-aHYtLmQ8HY-GjPRB-5toc1DfVcOBvqCehKbTFM~tyi4uCkZxu2cSAwR0fbOehPENIleUpJeMMsfTUYeRQWThWIebUlLCCJe41YjklJl85ni4Hrs64~HtXRp7wcAc80omfGpmC7ch2FQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA`

to avoid multiple redirects.

I didn't test the plugin yet, but the preview looks interesting.

**Comment by pauloamgomes** [comment]
@raffaelj  thanks for reporting.
