### ISSUE TITLE
pulling  other attributes from collection links

### ISSUE THREAD

**Issue by AKApumkin** [pauloamgomes/Cockpit-MultipleCollectionLink#4]
Hi there, not sure how to achieve the following, its partially working. 

in the JSON options declaration for the multi collection field, i want to be able to pull additional information from the collections. In the API response i can see it defined in the fields object, but the entries object does not show it. I have tried to add an extra field in the .tag file in the entry object declaration statement as well, but that didn't work. 

```
{
  "links": [
    {
      "name": "blog_items",
      "display": "fieldname",
      "title" : "title",
      "image": "image"
    },
    {
      "name": "use_case_items",
      "display": "fieldname"
    }
  ],
  "limit": false,
  "viewMode": "list"
}
```

**Comment by pauloamgomes** [comment]
HI @AKApumkin , not sure if understood properly, but the idea of collection links is just to save a reference to the linked collection entry (entry _id), and few metadata (collection type and display) to be used on the UI. Any information that is part of the linked collection entry is not stored, and should be accessed when fetching the api (using populate=1)

**Comment by AKApumkin** [comment]
Hey Paul, 

Yep i didn't get the idea of collection link. populate=1 does exactly what it says on the tin :D we all good now.

Cheers,
